builds:
  -
    id: lambo
    main: ./cmd/lambo
    binary: lambo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  -
    format: binary
    name_template: "{{ .Binary}}.{{ .Os }}.{{ .Arch }}"

release:
  github:
    owner: liamg
    name: lambo

dockers:
  - 
    goos: linux
    goarch: amd64
    ids:
    - lambo

    dockerfile: Dockerfile
    skip_push: auto
    image_templates:
    - "ghcr.io/liamg/lambo:latest"
    - "ghcr.io/liamg/lambo:{{ .Tag }}"
    - "ghcr.io/liamg/lambo:v{{ .Major }}.{{ .Minor }}"
